services:
  ocr:
    container_name: ocr_service
    image: c0deplayer/dc-ocr:main
    ports:
      - "8080:8080"

  processor:
    container_name: processor_service
    image: c0deplayer/dc-processor:main
    ports:
      - "9090:9090"
    depends_on:
      - ocr