version: '3'
services:
  ocr:
    container_name: ocr_service
    build:
      dockerfile: Dockerfile.ocr
    ports:
      - "8080:8080"

  processor:
    container_name: processor_service
    build:
      dockerfile: Dockerfile.processor
    ports:
      - "9090:9090"
    depends_on:
      - ocr