FROM python:3.12
LABEL authors="codeplayer"

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src/documentclassification/ocr/ /code/documentclassification/ocr/

CMD ["fastapi", "run", "documentclassification/ocr/ocr.py", "--port", "8080"]