FROM python:3.12
LABEL authors="codeplayer"

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src/documentclassification/process/ /code/documentclassification/process/

CMD ["fastapi", "run", "documentclassification/process/process.py", "--port", "9090"]