services:
  ocr:
    container_name: ocr_service
    image: c0deplayer/dc-ocr:main
    # build:
    #   dockerfile: Dockerfile.ocr
    ports:
      - "8080:8080"
    networks:
      - document-classification
    volumes:
      - type: bind
        source: logs
        target: /app/data/logs
      - type: bind
        source: models
        target: /app/data/models

  processor:
    container_name: processor_service
    image: c0deplayer/dc-processor:main
    # build:
    #   dockerfile: Dockerfile.processor
    ports:
      - "9090:9090"
    networks:
      - document-classification
    depends_on:
      - ocr
    volumes:
      - type: bind
        source: logs
        target: /app/data/logs
      - type: bind
        source: models
        target: /app/data/models
  

  predictor:
    container_name: predictor_service
    image: c0deplayer/dc-predictor:main
    # build:
    #   dockerfile: Dockerfile.predictor
    ports:
      - "7070:7070"
    networks:
      - document-classification
    depends_on:
      - processor
    volumes:
      - type: bind
        source: logs
        target: /app/data/logs
      - type: bind
        source: models
        target: /app/data/models



networks:
  document-classification:
    driver: bridge