[project]
name = "DocumentClassification"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    { name = "Jakub Zenon Kujawa", email = "ZK_Jakub@proton.me" },
]
dependencies = [
    "torch>=2.5.0",
    "torchvision>=0.20.0",
    "torchaudio>=2.5.0",
    "huggingface-hub[torch]>=0.26.1",
    "easyocr>=1.7.2",
]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = { text = "MIT" }


[tool.pdm]
distribution = false
