name: Build and Push Docker Images
on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"
    branches:
      - main
  schedule:
    - cron: "30 16 * * *"

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: c0deplayer/dc-ocr
            dockerfile: ./Dockerfile.ocr
          - image: c0deplayer/dc-processor
            dockerfile: ./Dockerfile.processor
          - image: c0deplayer/dc-predictor
            dockerfile: ./Dockerfile.predictor

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.template .env
          echo "" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
