name: Lint and Commit
on:
  push:
    paths:
      - '**.py'
    branches:
      - main
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - uses: astral-sh/ruff-action@v1
      with:
        changed-files: "true"
        
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'style: Style fixes by ruff'
